### ISSUE TITLE
In Android Version 13, the Screen Sharing feature is broken

### ISSUE THREAD

**Issue by nitinbehal1212** [jitsi/jitsi-meet#13621]
In Android 13 the screen share feature is not working.  

The issue is easily reproducible in the sample app also. If we set the target and compile SDK to 33 (Android 13).  

The compile and target SDK should be 33 per google play store guidelines.  And Existing Apps also have a deadline of August to migrate to 33.

**Comment by saghul** [comment]
Broken, how?

**Comment by nitinbehal1212** [comment]
Broken, means When we start start screen sharing in Android 13,  the mobile get's hanged and shows ANR(App Not Responding.)

**Comment by saghul** [comment]
Do you observe that with the Jitsi Meet app or a different one using our SDK, and if so, what version?

**Comment by nitinbehal1212** [comment]
We have Integrated Jitsi SDK Version 8.2.2 and set the compile and target SDK 33 Instead of 32.

**Comment by saghul** [comment]
Thanks, we'll take a look!

**Comment by jaswant-saini** [comment]
Hi @saghul,
Any updates on this??
I'm also facing the same problem.

**Comment by mhamed0httb** [comment]
I also got the same problem with **Jitsi** version 6.0.0, **compileSdkVersion** 33, running on Android 13 with Samsung Galaxy S21, we are using the sdk with our app, when trying to share the screen, the ANR dialog appears, is there any possibility to identify the problem ?

**Comment by Fatiharclk** [comment]
I also get the same error after a while after screen sharing. Do you have any updates available?

**Comment by saghul** [comment]
> I also got the same problem with **Jitsi** version 6.0.0, **compileSdkVersion** 33, running on Android 13 with Samsung Galaxy S21, we are using the sdk with our app, when trying to share the screen, the ANR dialog appears, is there any possibility to identify the problem ?

SDK 6.0.0 is very old at this point and won't be getting any fixes.

A fix will come to SDK 8, once ready.

**Comment by gauravdua27** [comment]
Hi @saghul ,  
Any updates on this?
I'm also facing the same problem.

**Comment by saghul** [comment]
No updates yet, sorry.

**Comment by saghul** [comment]
Should have been fixed by https://github.com/jitsi/jitsi-meet/commit/83e404266898bfb3f768892d0b6ab63146446da1

**Comment by nitinbehal1212** [comment]
Thank you @saghul , But one query When you are planning to release the mobile SDK with this fix?

**Comment by saghul** [comment]
We'll do some app betas first. A few weeks.

**Comment by saghul** [comment]
I have not been able to reproduce that.

Can you please provide some crash logs.

**Comment by michellavezzo** [comment]
@saghul I ran some tests in my Galaxy S9 android 10, I got these logs:
Android 10 seems good, but my S10, android 12, has the same issue.

I tried to update the `"react-native-screens": "3.25.0",`  but seems still not working

![WhatsApp Image 2023-10-06 at 18 05 09](https://github.com/jitsi/jitsi-meet/assets/38358577/e8bdd81e-ceff-4693-bf6a-730fd8b19a9f)
![WhatsApp Image 2023-10-06 at 18 05 09 (1)](https://github.com/jitsi/jitsi-meet/assets/38358577/af0fa43f-c1ca-4cd0-91f3-bf0b99156451)

**Comment by saghul** [comment]
@michellavezzo I don't understand how that is related to the original issue here.

**Comment by nitinbehal1212** [comment]
@saghul , there is an issue in the latest SDK version 8.4.0.   In Android 11 when you do screen share the participants will see the screen share as flickring. And In Android 13 the screenshare to participants is lagging a lot. So, after bumping the target and compile SDK to 33 this new issue occurred.

Before these SDK release everything worked fine in Android below 13. But now below 13 also has issues with screenshare.

You easily test these issues in the live Android Jitsi Meet app.

**Comment by saghul** [comment]
Are you testing on meet.jit.si or another deployment?

**Comment by nitinbehal1212** [comment]
We have tested this issue on our deployment and also tested this on jitsi official app on google play store  with default meet.jit.si 

Screenshare is not working well at the participant side.

**Comment by saghul** [comment]
I'll give it another go. This is very strange as we made no changes to that functionality, other than making the whole SDK compatible with API level 33, which involved bumping some dependencies, none of which have anything to do with screen sharing...

**Comment by nitinbehal1212** [comment]
Thanks, @saghul , if possible can you move this issue to open from close?

**Comment by michellavezzo** [comment]
> @michellavezzo I don't understand how that is related to the original issue here.

I was wondering if this memory leak has something about the Screen Share, I'm investigating, If I find something, I'll share it.

**Comment by saghul** [comment]
> > @michellavezzo I don't understand how that is related to the original issue here.
> 
> I was wondering if this memory leak has something about the Screen Share, I'm investigating, If I find something, I'll share it.

Unlikely, rn-screens is used for layout, not screen-sharing.
