### ISSUE TITLE
Failed to install desktop sharing extension

### ISSUE THREAD

**Issue by artooro** [jitsi/jitsi-meet#192]
Just got Jitsi Meet working on our own server, but we're having an issue with the screen sharing. The Chrome extension is installed and works great if we go to meet.jitsi.org but on our own site we get an error that says "Failed to install desktop sharing extension" and the following error appears in the javascript console.

```
Failed to obtain the stream to switch to Installs can only be initiated by one of the Chrome Web Store item's verified sites 
```

Screen sharing is pretty important and this seems like it should be a simple fix. For example you shouldn't try to install the extension directly, but instead link to the chrome web store. And also detect if the extension is already installed which it is in our case.

**Comment by serviewcare** [comment]
I've built my own extension with a URL in the Chrome App store, but I'm still getting an issue with the latest Jitsi Meet Source code:

"Uncaught Chrome Web Store installations can only be initated by a user gesture."

**Comment by sheaw** [comment]
Has there been any follow-up to this thread?  "serviewcare" ? were you able to resolve the issue ?

**Comment by paweldomas** [comment]
```
"Uncaught Chrome Web Store installations can only be initated by a user gesture."
```

The error above has been fixed with [this] commit.

[this]: https://github.com/jitsi/jitsi-meet/commit/cd19c0e9e314dfe6837a4e9a1c05083cb236c52b

More info on:
```
Failed to obtain the stream to switch to Installs can only be initiated by one of the Chrome Web Store item's verified sites
```
can be found [here].

[here]: https://developer.chrome.com/webstore/inline_installation#verified-site

**Comment by YoussF** [comment]
Hi i'm facing the same issue, i cloned this repo (https://github.com/jitsi/jidesha) edited manifest.json to change the domain information, the extension has been recompiled to .crx, i installed this new .crx extension but it still getting the same error.

Can someone please add to the documentation how to achieve this.

**Comment by AikedeJongste** [comment]
@YoussF I had to update the id in the config file on my server /etc/jitsi/meet/servername.com-config.js - and I used Chrome Incognito mode to install it to prevent caching issues.

**Comment by y0zer** [comment]
Has anyone been able to get this working.
I followed the same at https://github.com/jitsi/jidesha
I have created the .crx file and enabled it in chrome.
I have also added the id in the /etc/jitsi/meet/servername.com-config.js
still get the same error message 
"permission denied, failed to install desktop sharing extension.

Please help!

**Comment by paweldomas** [comment]
See https://developer.chrome.com/webstore/inline_installation

**Comment by aderal000** [comment]
Same with me is this ext mus be published on Chrome store?

**Comment by YoussF** [comment]
I think so, I looks like Chrome extensions must be "listed in the Chrome Web Store".

Here is what i can read on the 'Chrome://extensions' page :

> This extension is not listed in the Chrome Web Store and may have been added without your knowledge [Learn More...](https://support.google.com/chrome/answer/2811969?visit_id=1-636111657306318768-1009044494&p=ui_remove_non_cws_extensions&hl=en&rd=1)

I googled for some  workaround, and there are some people that recommend to use a browser like Chromium or Canary... but i don't think it is the ideal solution.....

**Comment by myeasymeeting** [comment]
i already publish the sharing extension chrome its available now . its works when some one install on his /her chrome . but if he does not install the app its showing the error .

 here is the link of my site https://myeasymeeting.com

here is the link of my extention
https://chrome.google.com/webstore/detail/my-easy-meeting-desktop-s/dbbogjkhmflmmbbjoideogddohnjjloo/related

thanks 
ahmed

**Comment by williammahecha** [comment]
There is a Jitsi Implementation in Openfire Meetings extension, for Jitsi Videobridge pluggin.
After it is added to Chrome, you click on it for first time, and it asks for server-name to match the Jitsi private Videobridge Server.

Jitsi developers could make a similar implementation, and that way, Jitsi.org could publish a single Jitsi Videobridge Extension usable for all Private implementations.

**Comment by didierm** [comment]
Currently, we are still getting the same error message in the Rocket.Chat client.
Is this related to https://github.com/RocketChat/Rocket.Chat.Electron/issues/240 ?

**Comment by Ahmed** [comment]
Last step after building the extension on chrome is to change the `desktopSharingChromeExtId` in `/etc/jitsi/meet/*config.js` to the ID you have in chrome.

**Comment by designgurudotorg** [comment]
@Ahmed does that ID need to be available from the chrome store or should this work with a local extension on your computer?

**Comment by Ahmed** [comment]
Hmm, I don't remember the exact thing, but I remember I didn't publish
anything in Google chrome store. You change it to the one you built and
installed locally.

**Comment by designgurudotorg** [comment]
Looks like I have to submit it to the Chrome store... https://support.google.com/chrome/answer/2811969?visit_id=1-636244403542082915-3442393358&p=ui_remove_non_cws_extensions&hl=en&rd=1

**Comment by Ahmed** [comment]
you can build it and install it locally. I did that last time.

**Comment by designgurudotorg** [comment]
Published to the chrome app store et voila! It works :)

**Comment by thekyriarchy** [comment]
I'm getting this error when clicking the desktop sharing button on meet.jitsi.net (which doesn't even show up in firefox): "Permission denied: failed to install desktop sharing extension"

this is not on a custom domain. where can the extension even be found? I tried searching but all i could find were suspicious looking or third party ones

**Comment by damencho** [comment]
@thekyriarchy do you got the same error when using https://meet.jit.si ?

**Comment by thekyriarchy** [comment]
No. Why are the separate? Should one redirect to the other? Or at least be running the same software/settings?

**Comment by damencho** [comment]
Nope, this is a testing deployment and desktop sharing not working is expected behaviour. Where did you get the link by the way on the website there should be link only to meet.jit.si?

**Comment by thekyriarchy** [comment]
Ah, I see. Thanks for the explanation. It looks like #1749 has had the same problem. I think I must have come to it by accident. 

In this case, why not use a more clear domain such as meet-devel.jit.si instead of this confusing naming scheme?

**Comment by aaronkvanmeerten** [comment]
Its actually an experiment in wildcard domains. So anything.jitsi.net can
be used this way. The issue turns out to be screen sharing as you
discovered.

I'm glad we have cleared up this confusion for you

Cheers,

Aaron

**Comment by Ark74** [comment]
What about Firefox?
Have anyone build/tried the plugin?

**Comment by thekyriarchy** [comment]
Now I am getting the error on meet.jit.si

**Comment by damencho** [comment]
@thekyriarchy What is your browser version?

**Comment by thekyriarchy** [comment]
Firefox 58
