### ISSUE TITLE
iOS App crashing

### ISSUE THREAD

**Issue by zy885137** [jitsi/jitsi-meet#3126]
i am trying to integrate jitimeet in my app. i did all the steps as mentioned.
But after successful build, the app crashes with the following log.

 Unknown class JitsiMeetView in Interface Builder file.
 [UIView setDelegate:]: unrecognized selector sent to instance 0x7fcdbdd04420
 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIView setDelegate:]: unrecognized selector sent to instance 0x7fcdbdd04420'

Why is created the type of the UIView？

**Comment by saghul** [comment]
Looks like JitsiMeetView is not being recognized by IB. Did you properly add the Framework(s) to your project and included the header files?

**Comment by zy885137** [comment]
This project is also the same problem！[https://github.com/jitsi/jitsi-meet/tree/master/ios]

![1528787836550](https://user-images.githubusercontent.com/6452049/41275768-971a05f6-6e54-11e8-8623-d3ba7ed9ec8e.jpg)

**Comment by zy885137** [comment]
![image](https://user-images.githubusercontent.com/6452049/41275978-4458a740-6e55-11e8-9301-1fb5b4b0ced1.png)

**Comment by saghul** [comment]
> This project is also the same problem！[https://github.com/jitsi/jitsi-meet/tree/master/ios]

Of course not. We develop this every day and I can assure you it works properly.

Do you have your project's source code available anywhere?

**Comment by zy885137** [comment]
The issue is fixed. The Jitsi Meet SDK is working fine.
it is still setting ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES to YES！
Thank you again for the great to the Jitsi team.

**Comment by saghul** [comment]
Thanks @zy885137 ! I'll make a note so we include that in the SDK docs!

**Comment by xiaowasly** [comment]
I refer to the compilation method of the official website to export the SDK。
<img width="461" alt="123" src="https://user-images.githubusercontent.com/22368246/146327425-21aed196-dcfe-4790-9493-e199d6ffed57.png">

I setting ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES to YES  ，but the problem still exists.

**Comment by saghul** [comment]
Please open a new issue, this is is over 4 years old and it's unlikely anything in here applies today.
