### ISSUE TITLE
Android WebView: Uncaught ReferenceError: chrome is not defined

### ISSUE THREAD

**Issue by KBernard-nx** [jitsi/jitsi-meet#362]
I/chromium﹕ [INFO:CONSOLE(1477)] "This appears to be Chrome, ver: 46", source: https://meet.jit.si/libs/app.bundle.js?v=634 (1477)
 I/chromium﹕ [INFO:CONSOLE(0)] "Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.", source:  (0)
I/chromium﹕ [INFO:CONSOLE(12063)] "Using Chrome extension for desktop sharing", source: https://meet.jit.si/libs/app.bundle.js?v=634 (12063)
 I/chromium﹕ [INFO:CONSOLE(11948)] "Uncaught ReferenceError: chrome is not defined", source: https://meet.jit.si/libs/app.bundle.js?v=634 (11948)

any help would be appreciated. 
thanks.

**Comment by gpolitis** [comment]
I don't know which engine is bundled with the Android WebView, but it seems it offers the `webkitGetUserMedia` causing our app to think it's running on Chrome. Even if we fixed this specific exception, I suspect there will be more problems down the road. For reference, here's the code that fails:

```js
function checkChromeExtInstalled(callback) {
    if (!chrome.runtime) { // Uncaught ReferenceError: chrome is not defined on Android WebView
        // No API, so no extension for sure
        callback(false, false);
        return;
    }
    chrome.runtime.sendMessage(
        config.chromeExtensionId,
        { getVersion: true },
        function (response) {
            if (!response || !response.version) {
                // Communication failure - assume that no endpoint exists
                console.warn(
                    "Extension not installed?: ", chrome.runtime.lastError);
                callback(false, false);
                return;
            }
            // Check installed extension version
            var extVersion = response.version;
            console.log('Extension version is: ' + extVersion);
            var updateRequired
                = isUpdateRequired(config.minChromeExtVersion, extVersion);
            callback(!updateRequired, updateRequired);
        }
    );
}
```

**Comment by gpolitis** [comment]
@KBernard-nx this particular exception should be fixed in https://beta.meet.jit.si/. Could you please check if switching to beta fixes the issue for you?

**Comment by KBernard-nx** [comment]
Thank you George. 

i found that if i set the UA to 
Mozilla/5.0 (Linux; Android 4.1.1; HTC One X Build/JRO03C) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/26.0.1410.58 Mobile Safari/537.31
the video playback works perfect. 

the device i am testing on is a ATT Tab 4 10 Inch. T537A.

**Comment by gpolitis** [comment]
What's the original UA? Interestingly, we upgraded https://meet.jit.si/ yesterday evening. I'm wondering if it's the upgrade that fixed it or the UA modification.

**Comment by KBernard-nx** [comment]
Original UA : 
Mozilla/5.0 (Linux; Android 5.1.1; SAMSUNG-SM-T537A Build/LMY47X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/46.0.2490.41 Safari/537.36

just tried https://meet.jit.si/ now with this UA and still receiving the same error. same for beta. 

my guess it has to do with the Chrome version i'm sending to your site. 
hope this helps.

**Comment by jraghvan** [comment]
Hello,

Have a similar issue.  I have simple QML application That does nothing but just opens meet.jit.si  
I am seeing the same issue, Video capture is not turned on.  

My Env:

QT: 5.6 
QtWebEngine : 5.6

Sample QMLFile  (webengine.qml)

<snip>
import QtQuick 2.4
import QtQuick.Window 2.2
import QtWebEngine 1.2
import QtWebEngine.experimental 1.0
import QtQuick.Controls 1.2
import QtQuick.Controls.Styles 1.2
import QtQuick.Layouts 1.1
import QtQuick.Controls.Private 1.0

Window {
    visible: true
    width: 1300
    height: 900


    WebEngineProfile {
        httpUserAgent: "Mozilla/5.0 (X11; Linux i686; rv:10.0) Gecko/20100101 Firefox/10.0";
    }

    WebEngineView {
        id: webEngineView
        url: "http://meet.jis.si/"
        anchors.fill: parent
        anchors.margins: 10
        onFeaturePermissionRequested: {
            console.log("request")
            grantFeaturePermission(securityOrigin, feature, true);
        }

        readonly property string hideElementsJS: "
            function hideElement(id) {
                const el = document.getElementById(id);
                if (el) {
                    el.style.display = 'none';
                }
            }

            function hideElementsByClass(className) {
                const elList = document.getElementsByClassName(className);
                for (var i = 0, n = elList.length; i < n; ++i) {
                    elList[i].style.display = 'none';
                }
            }

            hideElement('hnArea');
            hideElement('lxSocialBarWrapper');
            hideElement('footerContent');
            hideElement('ftDisclaimers');
            hideElement('bottomNav');
            hideElement('topLinks');
            hideElement('rightMenuButtons');

            hideElementsByClass('footerText');
            hideElementsByClass('disclaimers');
        "

        onLoadingChanged: {
            if(loadRequest.status === WebEngineView.LoadSucceededStatus) {
                console.log("start")
                runJavaScript(hideElementsJS);
                console.log("stop")
            }
        }
    }
}
</snip>

To run it, You would need Qt5.6,   qmlscene  ./webengine.qml

Any ideas what can be wrong here? 

BTW, if i replace,  url from "https://meet.jit.si/"  to   "https://opentokrtc.com/"  I am able to
get Video work fine.

Thanks,
Jayasimha

**Comment by bgrozev** [comment]
Probably fixed by now, please re-open if it happens
