### ISSUE TITLE
com.facebook.react.bridge.NoSuchKeyException: lineNumber

### ISSUE THREAD

**Issue by zhaozhilong001** [jitsi/jitsi-meet#4143]
com.facebook.react.bridge.NoSuchKeyException: lineNumber
	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:124)
	at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:128)
	at com.facebook.react.bridge.ReadableNativeMap.getInt(ReadableNativeMap.java:182)
	at com.facebook.react.util.JSStackTrace.format(JSStackTrace.java:28)
	at com.facebook.react.modules.core.ExceptionsManagerModule.reportSoftException(ExceptionsManagerModule.java:46)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:154)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
	at java.lang.Thread.run(Thread.java:761)

**Comment by saghul** [comment]
Is this the app or the SDK? Either way, what version?

**Comment by mt131** [comment]
https://github.com/jitsi/jitsi-meet-sdk-samples
it is on this app, crash when leave room

**Comment by saghul** [comment]
I cannot reproduce this, but this was fixed upstream in React Native: https://github.com/facebook/react-native/commit/d7bd6cce38d42dbced48fc8abed96472126e5d69

**Comment by shenjun100** [comment]
Same issue happens when i run jitsi-meet-sdk-samples on Android O and Android P devices.

**Comment by saghul** [comment]
I just tried again with the Android P simulator and cannot reproduce it. The fix already landed though, so the next SDK update will fix this.

Did you make any changes to the SDK or sample project at all?

**Comment by shenjun100** [comment]
Nope, direct installation from https://github.com/jitsi/jitsi-meet-sdk-samples with org.jitsi.react:jitsi-meet-sdk:2.1.0

**Comment by saghul** [comment]
Are you using a simulator? Which one?

**Comment by shenjun100** [comment]
I'm using actual devices: samsung galaxy S9 and S10.

**Comment by shenjun100** [comment]
Same issue does not happen when i install jitsi meet from play store. Only happens on the sdk sample project.

**Comment by saghul** [comment]
I think it's a RN 0.59.4 bug, which got fixed in 0.59.5. Can you try to build the SDK yourself from master and test it out? (it should be fixed there).

Also, a logcat might help. Thanks!

**Comment by shenjun100** [comment]
sure, will try it out, thanks

**Comment by mt131** [comment]
https://files.fm/u/gxd6tk55#/view/VID_20190506_083900.3gp;play

**Comment by saghul** [comment]
@mt131 See my suggestion above. Also, what Android version is that?

**Comment by mt131** [comment]
android 8.0 and android 8.1 also crash

**Comment by zayedelfasa** [comment]
i think upgrade react-native to 0.59.5 is the best solving. my project running well when upgrade it. thanks for cool jitsi project! nice!

**Comment by noloman** [comment]
hi,

I'm having the same issue with different devices running Android P.
This is the stacktrace if it helps:
```
com.myapp.debug E/AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
    Process: com.myapp.debug, PID: 1455
    com.facebook.react.bridge.NoSuchKeyException: lineNumber
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:124)
        at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:128)
        at com.facebook.react.bridge.ReadableNativeMap.getInt(ReadableNativeMap.java:182)
        at com.facebook.react.util.JSStackTrace.format(JSStackTrace.java:28)
        at com.facebook.react.modules.core.ExceptionsManagerModule.reportSoftException(ExceptionsManagerModule.java:46)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:193)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by saghul** [comment]
Yeah, this is known. It will be fixed on the next SDK update. In the mean time you can build the SDK from source, where this bug is fixed.

**Comment by noloman** [comment]
Thanks! When is the next release of this library planned?

Op ma 20 mei 2019 17:33 schreef Saúl Ibarra Corretgé <
notifications@github.com>:

**Comment by saghul** [comment]
"Soon" :-) (sorry, that's as precise as i can be)

**Comment by noloman** [comment]
Haha no prob, thanks!

Op ma 20 mei 2019 18:23 schreef Saúl Ibarra Corretgé <
notifications@github.com>:

**Comment by uraniumreza** [comment]
this issue has been resolved on `0.59.5` release
https://github.com/facebook/react-native/releases/tag/v0.59.5

**Comment by saghul** [comment]
Yes, we know and have bumbed the dependency already: https://github.com/jitsi/jitsi-meet/issues/4143#issuecomment-488582614 you can build the SDK from source or wait for a new SDK release which should happen soon.

**Comment by saghul** [comment]
Fixed in SDK 2.2.0, which was releaseed last week.

**Comment by Sathyanarayan09** [comment]
This issue is still there with react-native@0.59.9

**Comment by HarshitMadhav** [comment]
I was experiencing this same issue only on release mode of android app. I tried this and its working now
https://github.com/kmagiera/react-native-gesture-handler/issues/320#issuecomment-443815828

**Comment by lakshbhutani** [comment]
I am still not able to solve this issue even after upgrading react native to "0.59.5",

This is my stacktrace 

Fatal Exception: com.facebook.react.bridge.NoSuchKeyException: lineNumber
       at com.facebook.react.bridge.ReadableNativeMap.getValue + 124(ReadableNativeMap.java:124)
       at com.facebook.react.bridge.ReadableNativeMap.getValue + 128(ReadableNativeMap.java:128)
       at com.facebook.react.bridge.ReadableNativeMap.getInt + 182(ReadableNativeMap.java:182)
       at com.facebook.react.util.JSStackTrace.format + 28(JSStackTrace.java:28)
       at com.facebook.react.modules.core.ExceptionsManagerModule.reportSoftException + 46(ExceptionsManagerModule.java:46)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke + 372(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke + 158(JavaModuleWrapper.java:158)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback + 873(Handler.java:873)
       at android.os.Handler.dispatchMessage + 99(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage + 29(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop + 216(Looper.java:216)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run + 232(MessageQueueThreadImpl.java:232)
       at java.lang.Thread.run + 764(Thread.java:764)
