### ISSUE TITLE
[UI] Tile view does not act nice with narrow and tall windows

### ISSUE THREAD

**Issue by setpill** [jitsi/jitsi-meet#5142]
Steps to reproduce:
* Join a jitsi call with 6 people
* Enable tile view
* Make the screen narrow and tall

Expected behaviour:
* The tile view fills the available space in a 1-column 6-row grid.

Actual behaviour
* The tile view only uses a small portion of the available screen space in a 3-column 2-row grid.

**Comment by setpill** [comment]
Possibly related; if I'm reading the code correctly, the `min` and `max` functions are applied incorrectly [here](https://github.com/jitsi/jitsi-meet/blob/582d4aff1c110ba718a569540361c55f7c583795/react/features/video-layout/functions.js#L34). Seems like this would always return 5, unconditionally.

**Comment by saghul** [comment]
> Possibly related; if I'm reading the code correctly, the `min` and `max` functions are applied incorrectly [here](https://github.com/jitsi/jitsi-meet/blob/582d4aff1c110ba718a569540361c55f7c583795/react/features/video-layout/functions.js#L34). Seems like this would always return 5, unconditionally.

Good catch!

**Comment by fkleedorfer** [comment]
A narrow and tall, and  window is an important use case for playing certain online games, too. In that case, using the available space optimally (also, no jitsi logo) would be worth a lot.

**Comment by pmestrum** [comment]
I inspected the code.  There used to be a config variable TILE_VIEW_MAX_COLUMNS which is commented out, and is used in video-layout/functions.js getMaxColumnCount() function which indeed contains a bug and will always return 5.  

current code:
`    return Math.max(Math.min(configuredMax, 1), 5);`
should be:
`    return Math.min(Math.max(configuredMax, 1), 5);`

**Comment by pmestrum** [comment]
I fixed the bug and created a pull request

![image](https://user-images.githubusercontent.com/25814463/78422014-a2494100-765c-11ea-90c2-492be63a22a2.png)

**Comment by setpill** [comment]
@pmestrum I suspect this won't fix it for the following reasons

* A config value being commented out *by default* doesn't matter - it is still respected if an admin uncomments it on their instance.
* The fix to the min/max calculation is good, but the *maximum* amount of columns shouldn't dictate the *minimum* amount of columns.
* The proper fix would be to determine, based on the available dimensions for the grid and the number of meeting participants, what is the ideal layout that maximizes the size of each video.

**Comment by pmestrum** [comment]
Hi, @setpill. 
- I agree that uncommenting it doesn't matter.  I assumed it was commented out since it was not working, so for documentation reasons, I uncommented it again
- I don't agree with (or I don't understand) your second remark.  Since you should at least have 1 column (0 or negative doesn't make sense), it's a safetynet for invalid values.  Another way to deal with it is to throw an error, but I'm not mastering the whole project on that level to leverage that.
- having a smarter algorithm is indeed a better choice, but this is a bugfix, not an improvement.  The existing code is wrong, and it's blocking me of having it embedded in a proper way in my little project.

So, to be honest, I don't agree with your statement that my proposal is not fixing the issue.  The author (virtuacoplenny) obviously switched min & max, and he intended to implement it as I suggested now.

**Comment by setpill** [comment]
This issue (#5142) is about how the jitsi tile view acts in narrow/tall windows. My remark about the switching of the min/max functions is simply a side remark. Your PR therefore does not fix the issue as a whole (though I am happy you went and made it :+1:).

**Comment by setpill** [comment]
To expand on why your fix would not satisfy my usecase and maybe explain the "maximum vs. minimum amount of columns" remark - I manage a server that is used for meetups and meetings. I personally want to have the jitsi screen tucked into the left side of my screen, so I would want to have a 1- or 2-column view, but I do not want to dictate how other people use it. Maybe someone wants to have it tucked into the top of their screen instead. Or just use the whole screen, I don't know. If I set (server side) the max columns to 1, I would satisfy my own personal usecase, but at the detriment of those that use my server as well.

**Comment by setpill** [comment]
Here a javascript snippet that can be used to dynamically determine the appropriate number of columns to use:

```
function getTileViewColumns(gridWidth, gridHeight, tileRatio, numParticipants) {
    let bestColumns = 0;
    let bestTileWidth = 0;
    let bestFound = false;

    while (!bestFound) {
        const columns = bestColumns + 1;
        const straightTileWidth = Math.floor(gridWidth / columns);

        const rows = Math.ceil(numParticipants / columns);
        const straightTileHeight = Math.floor(gridHeight / rows);A

        const constrainedTileWidth = Math.ceil(straightTileHeight * tileRatio);

        const tileWidth = Math.min(straightTileWidth, constrainedTileWidth);

        if (tileWidth > bestTileWidth) {
            bestColumns = columns;
            bestTileWidth = tileWidth;
        } else {
            bestFound = true;
        }
    }

    return bestColumns;
}
```

NB: I am not a javascript dev, and I am not at home enough in this codebase to turn that into a PR. It should be run again every time any of the input parameters change (e.g. on window resize and participant connect/disconnect). It is optimized for readability not performance, though given that this is a javascript project I do not consider that a problem.

**Comment by fkleedorfer** [comment]
This seems right to me. If I am not mistaken this does exactly what I'd want as well.

**Comment by pmestrum** [comment]
@setpill I understand your reasoning. Setting the max on 1 is not done serverside.  It's part of the config used to initiate jitsi. But I don't think it's possible to change it when initialized.

The function or it's declaration doesn't exist in the project unfortunately.  So it will take some effort to refactor that.  I don't completely understand your algorithm but I know what the intension is: occupy as much space as possible with tiles, but I think it will always return 2.  Another approach could be to (optionally) set TILE_MIN_WIDTH and TILE_MAX_WIDTH.  If I have time, I'll think see what I can do.

**Comment by pmestrum** [comment]
I didn't test my fix, but I see another potential bug in the function where this 'getMaxColumnCount()' is called:
`/**
 * Returns the cell count dimensions for tile view. Tile view tries to uphold
 * equal count of tiles for height and width, until maxColumn is reached in
 * which rows will be added but no more columns.
 *
 * @param {Object} state - The redux store state.
 * @param {number} maxColumns - The maximum number of columns that can be
 * displayed.
 * @returns {Object} An object is return with the desired number of columns,
 * rows, and visible rows (the rest should overflow) for the tile view layout.
 */
export function getTileViewGridDimensions(state: Object, maxColumns: number = getMaxColumnCount()) {
    // When in tile view mode, we must discount ourselves (the local participant) because our
    // tile is not visible.
    const { iAmRecorder } = state['features/base/config'];
    const numberOfParticipants = state['features/base/participants'].length - (iAmRecorder ? 1 : 0);

    const columnsToMaintainASquare = Math.ceil(Math.sqrt(numberOfParticipants));
    const columns = Math.min(columnsToMaintainASquare, maxColumns);
    const rows = Math.ceil(numberOfParticipants / columns);
    const visibleRows = Math.min(maxColumns, rows);

    return {
        columns,
        visibleRows
    };
}
`
if maxColumns ==1, then visibleRows == 1 too.  So if we want all tiles in 1 big column, it won't work !  
My fix is already on the master branch. So let's see what the result is.  Is it easy to build and deploy locally to test ?

**Comment by setpill** [comment]
Hm, in tile view mode people do see themselves, so the comment in that screenshot confuses me.

**Comment by setpill** [comment]
If this `getTileViewGridDimensions` function is used, it looks like my function could be implemented inside it.

`columnsToMaintainASquare` is kind of wrongly named, since with a default aspect ratio of 16/9 of a tile, that's hardly a square. But good catch, it's definitely strange that `visibleRows` is constrained to `maxColumns`. I wonder if this function is used at all, then, because I think I've had meetings with more than 25 people without tile view issues.

**Comment by setpill** [comment]
Just tested, I could easily (aside from chromium overwhelming my CPUs) connect to the same meeting 30 times and have a nice 5x6 grid view.

**Comment by pmestrum** [comment]
nice.  I already deployed and debugged on my pc, and this function is entered.  So it needs further investigation and optimization.

**Comment by MurzNN** [comment]
Bump, this is still annoying!

**Comment by danionescu2007** [comment]
+1 for a fix on this issue

**Comment by NiallTracey** [comment]
Any update? I'm working on a collaborative app and was intending to use Jitsi for real-time video chat to allow discussion to continue while working. My layout is fully responsive... except for the camera tiles inside Jitsi, and I'm getting a lot of wasted screen real-estate, particularly as my window gets narrow.

I was hoping to make a "sidebar" option for tasks that need a large working area, but that's doesn't work with the Jitsi codebase as it is.

**Comment by NiallTracey** [comment]
I think it's also worth adding that the contrary problem also exists -- if I have a short and wide window, it doesn't attempt to put everything on a single row. If I connect 3 calls to the same meeting and switch to tile view, then it will show a row of 2 followed by a  row of 1, and will retain this layout until I shrink the window to the point that individual videos are only a few pixels tall.

**Comment by mrvnklm** [comment]
> I think it's also worth adding that the contrary problem also exists -- if I have a short and wide window, it doesn't attempt to put everything on a single row. If I connect 3 calls to the same meeting and switch to tile view, then it will show a row of 2 followed by a row of 1, and will retain this layout until I shrink the window to the point that individual videos are only a few pixels tall.

True that, facing that issue at the moment, but didn't manage to fix it properly yet. Do you have an idea for a workaround?

**Comment by NiallTracey** [comment]
For the moment, I’m just setting my webpage to only ever show Jitsi in a div of roughly screen-sized proportions. That means in a full-sized window on a desktop, it’ll be one quarter of the screen (half-width, half-height) rather than a full side of the screen. On a phone in portrait, I just set it to fill the width and set height to ¾ of screen width. I need to go back and make it more responsive to deal better with in-between shapes and sizes, but I’ve got more important parts to work on for now, and the main use-case is for a full-screen app anyway so time spent on making that part better isn’t much value right now.
Plus, I’m hoping this gets patched soon anyway as a fully reactive layout fits my initial concept better anyway. 😁

**Comment by Torgen** [comment]
For me, #filmstripRemoteVideos having 100px top and bottom margins makes it completely useless in an iframe with a height less than 232px, and even then it has a lot of wasted space. Making that aspect of it responsive is just the first step, since other math about the thumbnail sizes seems to be based on it, but it's clearly a necessary step.

**Comment by GeoTimber** [comment]
+1 for a fix on the issue, either dynamic or programmatic, let me change the max tile columns on the fly after initialization.

**Comment by tremby** [comment]
I had a video chat window side by side with a party game yesterday and was disappointed with all the wasted space.

I don't have time to dive in to the UI source code properly right now and orient myself, but I quickly threw together this example of a naive algorithm to find the ideal number of rows and columns.

https://codepen.io/tremby/pen/KKNwxBK -- public domain; do what you want with it.

This example looks at the available size, the aspect ratio of the participant videos, and the number of participants, it takes into account the minimum desired gap between rows/columns, and then chooses the number of rows and columns which allows the biggest possible videos. It's a dumb approach, starting with one column and increasing that until the video area stops increasing. I'm sure there's a better way to do it, but this works, and IMO this is not a performance-critical routine given that it only needs to run on participant join/leave and on viewport resize.

I did have a quick go at playing with the UI source. There are a lot of pieces whose purpose and importance I'm not sure of. For example:

- There's [this comment](https://github.com/jitsi/jitsi-meet/blob/master/react/features/video-layout/functions.js#L90-L91) which says to reduce the participant count by one before calculations if in tile mode because you can't see yourself, but you *can* see yourself, so I don't know what's going on there.
- Then there's also [various code to enforce a certain number of columns for particular viewports widths etc](https://github.com/jitsi/jitsi-meet/blob/master/react/features/video-layout/functions.js#L57-L70), which it seems to me would be pointless with an area-maximizing routine like this.
- There are [some constants or config options or something](https://github.com/jitsi/jitsi-meet/blob/master/react/features/video-layout/functions.js#L7-L11) which all look like they'd no longer be necessary, but maybe I'm missing some important requirement.

If someone experienced in the Jitsi Meet UI source can give me some guidance I can spend a bit of time on it and open a PR. Or if anyone wants to take my example, or take it in another direction, by all means go ahead.

**Comment by GeoTimber** [comment]
I found a workaround that worked for me was adding a customizing CSS file.

If you have control over the jitsi server, add the file to ```usr/share/jitsi-meet/css``` and then modify ```plugin.head.html``` in ```/usr/share/jitsi-meet``` to include that file, not sure if it will survive update te but keeping an eye on that now.

But a better solution is wished for, allow your own css overrides from the JITSI iframe API would be good..

```
/* 
 * CUSTOM  CSS FOR JITSI 
*/


@media (max-width: 500px) {

    .tile-view .remote-videos-container .videocontainer {  
        width: 80%!important;
        padding-top: 45%!important;
    }

    #localVideoTileViewContainer {
        width:100%;
    }

    .tile-view #localVideoTileViewContainer .videocontainer {
        width: 80%!important;
        padding-top: 45%!important;
        margin: auto;
    }

}
```

**Comment by johntyree** [comment]
@tremby your code would be improvement over jitsi today, but I don't think it is doing what you claim (maximizing area). Comparing 9-cells and 10-cells make it obvious enough that the 10 layout has bigger cells than the 9 layout. In general it seems that when the number of cells is a perfect square, it would rather make a square layout than maximize size.

**Comment by johntyree** [comment]
Your assumption here was wrong: `// Start at one column and increase until the cell area is getting smaller`

Adding one column might not be enough to get rid of a row (and vice versa), causing cell size to shrink, but getting rid of a sufficiently empty row will cause cell size to grow again. This relationship depends on the aspect ratios of the viewing area and the cells.

We could do some fancy geometry to get an optimal algorithm, or we could just sweep from 1xN to Mx1 and take the best.

```javascript
  let best = getCellSize(1);  // Start at 1 column
  let contender = best;
  while (contender.rows > 1) {  // End when there's only 1 row
    contender = getCellSize(contender.columns + 1);
    if (contender.area > best.area) {
      best = contender;
    }
  }
```

If we want to avoid touching (M+N) iterations we can compute directly what the best N is for a given M just try those.

```javascript
  // Add columns until we hit maximal video area. 
  let best = getCellSize(1);
  let contender = best;
  while (contender.rows > 1) {
    // Many columns do we need to shrink by one row?
    columns = Math.ceil(numCells / (contender.rows - 1)); 
    contender = getCellSize(columns);
    if (contender.area > best.area) {
      best = contender;
    }
  }
```

I couldn't figure out how to fork tremby's example, but here it's copy pasted with this change. https://codepen.io/johntyree/pen/ZEBrjxE

**Comment by tremby** [comment]
Ah, well spotted. Yes, I should have kept the full sweep rather than
exiting early.

**Comment by NiallTracey** [comment]
> Adding one column might not be enough to get rid of a row (and vice versa), causing cell size to shrink, but getting rid of a sufficiently empty row will cause cell size to grow again. This relationship depends on the aspect ratios of the viewing area and the cells.
> 
> We could do some fancy geometry to get an optimal algorithm, or we could just sweep from 1xN to Mx1 and take the best.

The algorithm isn't all that complicated really.

If you take the aspect ratio of the render area ... ar_render
and you take the aspect ration of the individual video cells... ar_video

then divide ar_render/ar_video (*) then you _should_ get the aspect ratio of the optimal layout = ar_layout

If ar_layout == 1, then the theoretical optimal layout is a grid with an equal number of rows and columns.

If ar_layout == 2, the theoretical optimum is twice as many columns as rows;
if ar_layout == 0.5, twice as many rows as columns.

Of course, ar_layout isn't likely to represent a rational fraction except on very rare occasions, and even when it does, it isn't likely that the number of tiles can be split by that exact ratio.

Say you have 4 tiles, and ar_layout = 3

You can't get a ratio of 3:1 out of 4. The theoretical optimum is 3:4/3, or 3:1.3333. 
That gives us an integer for the number of columns and a fraction for the number of rows.

If we just round up the fraction, we get a first approximation of 3 columns, 2 rows. Not totally useless, but 2 out of 6 cells are empty, so let's shrink it.
If we reduce the number of rows, we get a 3x1 grid which only has 3 cells, so we can discard that as not a solution. If we expand it by 1, we get 4x1, which is a viable solution.
If we reduce the number of columns, we get a 2x2 grid of 4 cells.

With a few divisions, a handful of comparisons, 2 -- operations, and at most 2 ++ operations, we are left with the only two feasible candidates for the optimum number of rows and/or columns. All that's left is to calculate the width (or height) of the individual cells in the two, and pick whichever is bigger.

Don't really have my head together enough to work this out exactly-- it's getting pretty late here and I've been watching the MCU with a large beer after a heavy day.
Sorry if it's not as clear as it could be, but I know I'd forget by morning if I didn't write anything down. I'll leave this tab open to remind me to code it up in the morning.

**Comment by NiallTracey** [comment]
"_The algorithm isn't all that complicated really._"

He says, before describing something that involves algebra and factorisation, so getting around that isn't straightforward.

Here's [a C# implementation of an almost-optimised version with a description of the algorithm](https://www.codeproject.com/Articles/217640/Tile-Scaling-for-Maximum-Area-Coverage-Based-Upon)

**Comment by johntyree** [comment]
Yes it is possible to limit the number of solutions by considering the aspect ratios, but I don't think we should adopt the example you showed for the following reasons.

1. The algorithm as written is way shorter.
    Most of it is actually dealing with gathering the inputs, meaning that the aspect-ratio algorithm will need to do this as well and the difference will be even larger.

2. The range of inputs is tiny. The worst we could possibly do is one check per cell and we're already doing better than that. The speedup of doing this very efficiently is unnoticeably small. Console.log the loop and see.

3. The correctness of the aspect-ratio example is difficult enough to understand that this person wrote a blog post about it. Despite all their effort, the post ends with,

> One thing to take note of is the fact that although the algorithm correctly finds all cases that I have tested, it is not all solved linearly. Most of it is, but there are still those few cases for which I had to 'brute force' my way through. You can see this in the code.

I think maintainability matters more here. You could implement this other one and show that it isn't so bad if you're not convinced. I'd love to be wrong.

**Comment by tremby** [comment]
Still matters

**Comment by johntyree** [comment]
I'm confused as to what is holding this up. We have a working implementation at this point. Are we just waiting for someone to make a PR out of it?

**Comment by hypergig** [comment]
> I found a workaround that worked for me was adding a customizing CSS file.
> 
> If you have control over the jitsi server, add the file to ```usr/share/jitsi-meet/css``` and then modify ```plugin.head.html``` in ```/usr/share/jitsi-meet``` to include that file, not sure if it will survive update te but keeping an eye on that now.
> 
> But a better solution is wished for, allow your own css overrides from the JITSI iframe API would be good..
> 
> ```
> /* 
>  * CUSTOM  CSS FOR JITSI 
> */
> 
> 
> @media (max-width: 500px) {
> 
>     .tile-view .remote-videos-container .videocontainer {  
>         width: 80%!important;
>         padding-top: 45%!important;
>     }
> 
>     #localVideoTileViewContainer {
>         width:100%;
>     }
> 
>     .tile-view #localVideoTileViewContainer .videocontainer {
>         width: 80%!important;
>         padding-top: 45%!important;
>         margin: auto;
>     }
> 
> }
> ```

For what it is worth, I believe custom css injection would address the issue I am having.

I filled my narrow iframe by setting with a little `display: flex` on the parent holding the video spans, and changing the video to `cover`. I was able to fill up all the space with just that.

Clearly this only works while using the dev tools as you can't touch the iframe code for real.

![Screen_Shot_2021-09-30_at_11.59.12_AM~2.png](https://user-images.githubusercontent.com/8643560/135613907-73cee0a6-5b1e-4feb-a43e-7042687e7d01.png)

**Comment by saghul** [comment]
AFAIK nobody has sent a PR. IF you do, @ me and I'll get it reviewed.

**Comment by th0rn** [comment]
@saghul Seems to work now (tiles in tall and thin windows tile reasonably) - I guess something was fixed somewhere else. Perhaps this can be closed now?

**Comment by saghul** [comment]
A lot has changed indeed!

**Comment by johntyree** [comment]
Narrow and tall looks pretty good now. Wide and short doesn't, but it's probably much less common, given that most people have wide screens rather than tall screens.
