### ISSUE TITLE
Shared document (Etherpad) closes automatically.

### ISSUE THREAD

**Issue by stonerl** [jitsi/jitsi-meet#5785]
## Description
When one opens the shared document (Etherpad) it gets closed as soon as another person speaks and that person's video gets focused. The only way to circumvent this at the moment, is to focus on the own video before opening etherpad.

## Current behavior
Dominant speaker gets focus and the shared document is closed.

## Expected Behavior
Shared document stays open even if other people speak.

## Possible Solution
Disable dominant speaker gets focus while shared document is open. Enable it when the shared document gets closed. 

## Steps to reproduce
- Open a meeting with 3 or more people. 
- Open shared document.
- Let the dominant speaker change
- Shared document gets closed.

# Environment details
The Latest docker image: `4384-1`

**Comment by sunweaver** [comment]
I see this exact problem on my local deployment of Jitsi meet. This is a very annoying bug for those who want to use Etherpad during Jitsi sessions. It makes the Etherpad integration nearly unusable.

**Comment by sunweaver** [comment]
I just upgraded to jitsi-meet DEB version 2.0.4455-1 and the issue seems to be resolved.

**Comment by stonerl** [comment]
Yes, it is fixed in the web version. The electron-app still has this issue.

**Comment by stonerl** [comment]
I'm reopening this, since the bug has been introduced again.

**Comment by ryanmartinneutrino** [comment]
When the pad is open, it closes as soon as a different person start talking (and the big screen would normally switch to them, but it shouldn't when a pad is open)

Confirming that this is still an issue, as reported in the docker section of the repository (https://github.com/jitsi/docker-jitsi-meet/issues/610#issuecomment-643755607).

**Comment by ashirwad007786** [comment]
I'm also facing this bug for a long time. 

@damencho @saghul Can we prioritize this bug? This bug discards the experience of the Shared Document.

**Comment by ashirwad007786** [comment]
This issue also happens if someone joins or leaves the room, then the whiteboard closes automatically.

**Comment by slincem** [comment]
I'm having the same issue. And I wanted to ask you... When you guys open the shared document, does it also opens for the other people in the room?. In my case everyone has to open it on their own, and I think when the moderator shares it, it should open for everyone by default; but I'm not sure if this is the expected behaviour

**Comment by jmkrishna** [comment]
I am also using Etherpad/WBO in Jitsi-meet. Continuously losing Focus while editing the pad/board.
Please help me if you have any solution.

**Comment by Patrick-Vogt** [comment]
Are there any news regarding this issue?
Would it help to remove the specific css, i.e. that there is no colored border around the active speaker?

**Comment by tusharsonawanes** [comment]
I am facing the same issue in my latest 5963 release. Can anybody reconfirm this?
