### ISSUE TITLE
Audio output crackling on iOS Safari -"Launch in web"

### ISSUE THREAD

**Issue by crprata** [jitsi/jitsi-meet#7421]
### Description:

After some time participating in a meeting on meet.jit.si and using Safari on iOS (Launch in web) with more than 3 participants, the audio starts to crack and gets worse until it is not possible to stay in the meeting.

### Steps to reproduce:

1. Enter in a room on meet.jit.si usando iOS Safari - "Launch in web"
2. If have more than 3 participants, after some minutes the audio output starts to crackling.
3. Spending more time in the meeting, the crackling increases until it is no longer possible to stay in the room. As new participants enter it gets worse.

### Server information:

- Jitsi Meet version: Latest Stable
- Operating System: Ubuntu 18.04 (it happens on meet.jit.si as well)

### Client information:

- Browser / app version: Safari
- Operating System: iOS 13.5.1 and 13.6 (Tested on iPhone X and iPhone 7)

**Comment by jallamsetty1** [comment]
Hey there, there are known issues with iOS Safari audio as reported in this webkit bug - https://bugs.webkit.org/show_bug.cgi?id=208233
The folks at Apple have been working on making various improvements that give higher priority to the audio module.
Do you see the same issue when you change the video quality settings under "Manage video quality" to send/receive lower resolution ? 
We have also deployed some changes to meet.jit.si that lower the client cpu utilization and the chance of audio drop outs decreases when the device is not doing intensive processing all the time. Please test against meet.jit.si and let us know if you see any difference there.

**Comment by crprata** [comment]
@jallamsetty1 thanks for you reply! The problem persists for me even in the latest stable version of jitsi (meet.jit.si), I've tested it on an iPhone 7 and iPhone X - iOS 13.6.1

**Comment by crprata** [comment]
@jallamsetty1 Do you have any idea how can I fix this?

**Comment by jallamsetty1** [comment]
> @jallamsetty1 Do you have any idea how can I fix this?

I am afraid the only way to mitigate this issue until Safari browser fixes land is to either mute video or select a lower send resolution via the "Manage video quality" settings from the 3 dots menu.

**Comment by jallamsetty1** [comment]
@crprata, were you able to try the suggestions mentioned above ?

**Comment by jallamsetty1** [comment]
Closing this issue since the above mentioned Safari bug and other audio related issue in iOS have been resolved in latest iOS release.
