### ISSUE TITLE
Video Audio Not Working in Jitsi Meet iOS (Failed to send E2E ping request or response)

### ISSUE THREAD

**Issue by alfinurhakim** [jitsi/jitsi-meet#7862]
### Description:
Hello friends, please help me ... I have an error that keeps me stuck for one week. I am very frustrated about this. this error is in the form of other participant's audio and video not working or not appearing on iOS however, on Android it runs well .. no matter what the problem I am very confused to solve.

I hope someone can solve this problem. Thank you

### Expected behavior:

Audio & Video Working in iOS

### Actual behavior:

Audio & Video Not Working in iOS

### Additional information:

This is the error log in xcode
<img width="328" alt="Screen Shot 2020-10-08 at 09 04 38" src="https://user-images.githubusercontent.com/48195224/95407167-7b8b0080-0946-11eb-912e-0b25064a73f7.png">

**Comment by Echolon** [comment]
Can you please describe the error in more details as well as steps to repeoduce?

**Comment by alfinurhakim** [comment]
> Can you please describe the error in more details as well as steps to repeoduce?

just do a regular conference and audio video is not working

![IMG_0390](https://user-images.githubusercontent.com/48195224/95422620-d84be280-0969-11eb-83c3-48f19132ac69.PNG)

**Comment by saghul** [comment]
Is this on your own instance? Are datachannels working correctly there?

**Comment by alfinurhakim** [comment]
> Is this on your own instance? Are datachannels working correctly there?

I took this photo of someone else's problem similar to mine ... the audio is not working and the video is not showing .. please help me :(

**Comment by saghul** [comment]
We cannot help you unless you give us more details. What SDK version are you using? Can you reproduce the problem against meet.jit.si?

**Comment by imdatsolak** [comment]
@saghul: just downloaded jitsi-meet, built an iOS client and tried a video-call. On the other side, I was using the JitsiMeet Desktop Client r2.0.2 on macOS Catalina. I connected to meet.jit.si.

The connection from the Desktop Client works - no problems there.

When I connect with the iOS-Client, the iOS client has neither Audio nor Video - meaning, it doesn't transfer anything.

In fact, the connection between the two clients (iOS and Desktop) seems never to be created - I believe this is an issue with P2P-connection there.

Both clients are in the same WiFi-network without any restrictions.

The iOS-Client showed following error:
![IMG_4205](https://user-images.githubusercontent.com/10852644/95759246-bd4eda80-0ca9-11eb-8ff1-d6ef365e6b1f.jpeg)

**Comment by imdatsolak** [comment]
Tried the same topic with:
- Two Desktop Clients (Jitsi Meet) from two different machines
- Two iOS Clients (iPadMini iOS 13.7 & iPhone SE 2 iOS 14.0.1)

All four devices connect to meet.jit.si to the same room

They all show up as participants with right names, etc and can also chat with each other - no problems there.

The iOS-Clients can neither send nor receive any audio or video. The Desktop-Clients work fine.

More debug info attached (from iPadMini iOS 13.7)

[xcode-debug-output2.txt](https://github.com/jitsi/jitsi-meet/files/5365930/xcode-debug-output2.txt)

**Comment by imdatsolak** [comment]
After some further analysis, it seems this is an issue here: https://github.com/jitsi/lib-jitsi-meet/issues/1296

**Comment by saghul** [comment]
I could reproduce this one and will be looking into it today.

**Comment by saghul** [comment]
This should now be fixed in master. Can you please try again?

**Comment by imdatsolak** [comment]
@saghul Thanks, it works now. I tested the Jitsi Meet iOS app as well as my own app/integration. Both work now - thank you very much.

**Comment by saghul** [comment]
Cheers!

**Comment by ardy0909** [comment]
I'm still facing this issue when trying to delete existing package-lock.json and then run npm install. I also got different number of lines in package-lock.json between existing package-lock.json (from repo) -> around 18k++ lines code and my own package-lock.json -> around 14k++ lines code

**Comment by fareed069417** [comment]
> This should now be fixed in master. Can you please try again?

Can you please share the exact commit which has solved this problem in master? @saghul

**Comment by saghul** [comment]
These 2: https://github.com/jitsi/jitsi-meet/commit/b891a7526d25f2713a896c8d91a6a42d6230b525 https://github.com/jitsi/jitsi-meet/commit/9434d3c34999c38847c337c6d8cfd319ac38aa3e there seems to be a weird combination of dependencies which break stuff.

I plan to fix this properly on react-native-webrtc, but I hadn't had the chance yet.

**Comment by fareed069417** [comment]
> These 2: [b891a75](https://github.com/jitsi/jitsi-meet/commit/b891a7526d25f2713a896c8d91a6a42d6230b525) [9434d3c](https://github.com/jitsi/jitsi-meet/commit/9434d3c34999c38847c337c6d8cfd319ac38aa3e) there seems to be a weird combination of dependencies which break stuff.
> 
> I plan to fix this properly on react-native-webrtc, but I hadn't had the chance yet.

Thanks @saghul. Let me go through it and see if i can make it work.

**Comment by ardy0909** [comment]
> These 2: [b891a75](https://github.com/jitsi/jitsi-meet/commit/b891a7526d25f2713a896c8d91a6a42d6230b525) [9434d3c](https://github.com/jitsi/jitsi-meet/commit/9434d3c34999c38847c337c6d8cfd319ac38aa3e) there seems to be a weird combination of dependencies which break stuff.
> 
> I plan to fix this properly on react-native-webrtc, but I hadn't had the chance yet.

@saghul based on this commit, I got this kind of error "[TypeError: undefined is not an object (evaluating 'eventTarget[LISTENERS][type]')]". May I know is this error comes because of react-native-webrtc or there are some dependencies that are missing?

**Comment by saghul** [comment]
That's the error, yes. It's some weird Babel thing. I plan to avoid it completely by making a fix in react-native-webrtc which would eliminate the offending code completely.

**Comment by uppuluriaditya** [comment]
@saghul : Thank you for the fix. When you say, fixing it in react-native-webrtc, does that mean, the standard react-native-webrtc or the one under Jitsi repo? I have forked Jitsi long ago and upgraded RN versions and all. My branch is completely off the track from current Jitsi. But I am facing this issue on iOS mobile client. I may not be able to use the same fix that was done here. If you could point the root cause, I can try to fix  it on my end. Is it something related to babel configuration?
Thanks in advance

**Comment by ardy0909** [comment]
> That's the error, yes. It's some weird Babel thing. I plan to avoid it completely by making a fix in react-native-webrtc which would eliminate the offending code completely.

Oh, I see. @saghul May I know why if I delete the existing package-lock.json and then I try npm install, It generates different package-lock.json ? In existing package-lock.json, It contains around 18k++ lines of code but in my package-lock.json, It only contains around 14k++

**Comment by saghul** [comment]
To clarify: the bug is caused by a weird interaction between Babel and this override: https://github.com/jitsi/jitsi-meet/blob/9742e90bb56a41b47a559ad88a78245905c4ec89/react/features/mobile/polyfills/RTCPeerConnection.js#L38

So, technically the bud is part of Jitsi Meet.

However, that code is necessary because of a bug (or rather mismatched behavior compating to browsers) of react-native-webrtc.

Moving forward, I'll fix the bug in RN-WebRTC so our override is not necessary and the bug will be avoided.

All eact-native-webrtc have this bug / mismatched behavior.

**Comment by uppuluriaditya** [comment]
Thank you @saghul  for the response. :) . In my case, the issue seems to be related to _RTCPeerConnection written as a function. I changed it to Class and it seems to be working. I guess till the fix for react-native-webrtc is available, i can live with this. But may i know what is the plan/probable timelines for the fix to be available in react-native-webrtc?

**Comment by saghul** [comment]
@uppuluriaditya Interesting! I tried that and didn't succeed. Mind making a PR with your changes?

**Comment by uppuluriaditya** [comment]
> @uppuluriaditya Interesting! I tried that and didn't succeed. Mind making a PR with your changes?

yes. That worked for iOS and for android i retained the old code itself as the class based declaration seems to be breaking for android.

**Comment by saghul** [comment]
Hum, interesting. Mind sharing it so we can maybe adjust it so it works for both?

**Comment by uppuluriaditya** [comment]
> Hum, interesting. Mind sharing it so we can maybe adjust it so it works for both?

sure. i will upload to my github and share you 👍

**Comment by uppuluriaditya** [comment]
> Hum, interesting. Mind sharing it so we can maybe adjust it so it works for both?

[Here](https://github.com/uppuluriaditya/RTCPeerConnection.git) is the link @saghul . I just converted the function into class... I am embedding it inside my custom app and everything seems to be working for both iOS and Android. Let me know if i can provide you with any further information. Thank you

**Comment by affereaflaw** [comment]
I used iOS SDK 2.11.0 and this problem sometimes occurred (audio not working) when I integrate default callkit to receive a call on locked device, and when I try to integrate with JMCallKitProxy the audio is not working at all.
Some of the logs :
- Bridge Channel send: no opened channel.
- Failed to send E2E ping request or response.

If anyone have sample to integrate callkit with jitsi, I'm really need help for this :)

thank you :)

**Comment by Extazx2** [comment]
I must say that @uppuluriaditya solution works but it gives me another error (not breaking it seems) with :

```
JSON value '(
        {
        bundlePolicy = "max-bundle";
        iceServers =         (
                        {
                credential = "MODIFIED";
                urls = "turns:turn-MODIFIED:443?transport=tcp";
                username = MODIFIED;
            }
        );
    },
        {
        optional =         (
                        {
                googHighStartBitrate = 0;
            },
                        {
                googPayloadPadding = 1;
            },
                        {
                googScreencastMinBitrate = 100;
            },
                        {
                googCpuOveruseDetection = 1;
            },
                        {
                googCpuOveruseEncodeUsage = 1;
            },
                        {
                googCpuUnderuseThreshold = 55;
            },
                        {
                googCpuOveruseThreshold = 85;
            },
                        {
                rtcStatsSFUP2P = 0;
            }
        );
    }
)' of type NSMutableArray cannot be converted to must be an object
```
In lieu and place of the breaking error fixed.

@saghul If there is a change, will it be in next mobile release ? 
@uppuluriaditya how do you link to the good RTCPeerConnection.js file within the app ?

**Comment by zvs001** [comment]
Thanks @uppuluriaditya . You saved me 👍 

About @Extazx2 error log https://github.com/jitsi/jitsi-meet/issues/7862#issuecomment-734763471: 
There is small mistake in updated file:
```
  constructor(...args: any[]) {
    super(args);
```

should be:
```
  constructor(...args: any[]) {
    super(...args);
```

**Comment by uppuluriaditya** [comment]
> I must say that @uppuluriaditya solution works but it gives me another error (not breaking it seems) with :
> 
> ```
> JSON value '(
>         {
>         bundlePolicy = "max-bundle";
>         iceServers =         (
>                         {
>                 credential = "MODIFIED";
>                 urls = "turns:turn-MODIFIED:443?transport=tcp";
>                 username = MODIFIED;
>             }
>         );
>     },
>         {
>         optional =         (
>                         {
>                 googHighStartBitrate = 0;
>             },
>                         {
>                 googPayloadPadding = 1;
>             },
>                         {
>                 googScreencastMinBitrate = 100;
>             },
>                         {
>                 googCpuOveruseDetection = 1;
>             },
>                         {
>                 googCpuOveruseEncodeUsage = 1;
>             },
>                         {
>                 googCpuUnderuseThreshold = 55;
>             },
>                         {
>                 googCpuOveruseThreshold = 85;
>             },
>                         {
>                 rtcStatsSFUP2P = 0;
>             }
>         );
>     }
> )' of type NSMutableArray cannot be converted to must be an object
> ```
> 
> In lieu and place of the breaking error fixed.
> 
> @saghul If there is a change, will it be in next mobile release ?
> @uppuluriaditya how do you link to the good RTCPeerConnection.js file within the app ?

I'm not sure of this error. But let me check and get back to you.

**Comment by uppuluriaditya** [comment]
> Thanks @uppuluriaditya . You saved me 
> 
> About @Extazx2 error log [#7862 (comment)](https://github.com/jitsi/jitsi-meet/issues/7862#issuecomment-734763471):
> There is small mistake in updated file:
> 
> ```
>   constructor(...args: any[]) {
>     super(args);
> ```
> 
> should be:
> 
> ```
>   constructor(...args: any[]) {
>     super(...args);
> ```

Thank you @zvs001 . You saved my day too :) .  I'll update the Fix in my branch. Thanks again
@Extazx2 Let me know how that goes.

**Comment by seolhyein** [comment]
@uppuluriaditya Thank you very much! It's 2 a.m in Korea. I couldn't go home because of this problem, but I solved it. You saved me :)

**Comment by Jacky-Rolo** [comment]
> This should now be fixed in master. Can you please try again?

Hi @saghul , may I ask what jitsi-meet fixed in master ?  
which commit fix this ?  

I used @uppuluriaditya 's RTCPeerConnection, and it's work. but I still want to figure out some of my other issue. 

many thanks

**Comment by puck08** [comment]
Hi together,
I have the same issue as well.
Using Jitsi Meet app version 21.5.0 build 146 on iOS 15.1 on iPad and iPhone.
By using a browser or Android everything is fine. Conference members using iOS are shown, but sound or camera pictures are not transferred.
Should it work after the above mentioned final statement with the current app version? Or do I have to adjust my configuration?
Thank you
