### ISSUE TITLE
Xcode 12.1 cannot build for Simulator

### ISSUE THREAD

**Issue by asnagni** [jitsi/jitsi-meet#8020]
### Description:

I upgraded to Xcode 12.1 and I'm using the Jitsi iOS sdk official release 2.10.2.
When I build for a device or I produce and archive everything works fine. Meaning that I can use the Jitsi libray within my App with no issue (The App runs and behaves properly). But when I try to build for the simulator (Any of them), the build will fail with this error:

ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/asnagni/project/system/BeBetter/libs/jitsi/ios/WebRTC.framework/WebRTC' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I'm not sure how to fix this issue since the Jitsi iOS sdk version 2.10.2 is supposed to work with Xcode 12.1

Anyone would have an idea on how to fix this issue?

Thank you,
Stay safe.

### Steps to reproduce:

1.  Migrate to Xcode 12.1
2.  upgrade to Jitsi iOS sdk version 2.10.2
3.  Build for Simulator (for example for the simulator iPhone 11 or 12)

### Expected behavior:

 The build should complete and you should be able with no error and you should be able to to run your App with Jitsi embedded into your App.

### Actual behavior:

 Th e build for the Simulator fails with this error:

ld: building for iOS Simulator, but linking in dylib built for iOS, file '/Users/asnagni/project/system/BeBetter/libs/jitsi/ios/WebRTC.framework/WebRTC' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Server information:

- Jitsi Meet version: 
- Operating System: 

### Client information:

- Browser / app version:  
- Operating System:  macOS Catalina  version 10.15.7

**Comment by infosteo** [comment]
Same error for me.

**Comment by asnagni** [comment]
Hi I infosteo. Did you have any chance with this issue.

Hi saghul, would you have any idea on how to solve this.

**Comment by saghul** [comment]
Try to add this to your project's Podspec file:

```
  s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
  s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
```

**Comment by asnagni** [comment]
Hi,
  First I would like to say thank you for reply, I do appreciate. Actually I’m using the released iOS sdk version 2.10.2 (JitsiMeet.framework & WebRTC.framework). I'm not building them. 

I don't build them. I just integrated them into the project. Please see attached screenshot.

<img width="1508" alt="Jitsi_issues_02" src="https://user-images.githubusercontent.com/37470668/98120957-a6e90880-1e7c-11eb-8406-53d0ac6136c3.png">

**Comment by saghul** [comment]
So you are embedding the frameworks by hand? In that case I think you can set `EXCLUDED_ARCHS[sdk=iphonesimulator*]` to `arm64` in the Build Settings tab.

**Comment by asnagni** [comment]
Hi Saghul,
  It's a bit different the way it is on Xcode 12. You have the "Excluded Architectures" with different options. I guess that you wanted meet to set:  **_arm64_** for "Any iOS simulator" ? Please see attached screenshot.


<img width="1508" alt="Jisi_issue_02" src="https://user-images.githubusercontent.com/37470668/98129364-09df9d00-1e87-11eb-8c4a-9895a222dfac.png">


When I build the App, I still have some error, but this time I have a different set of errors now. Please see the screenshot. I also copied and pasted the error so you can have it: 

<img width="1508" alt="Jisi_issue_03" src="https://user-images.githubusercontent.com/37470668/98129869-a0ac5980-1e87-11eb-81d7-6ce01ebb3ae4.png">



PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/asnagni/Library/Developer/Xcode/DerivedData/BeBetter-fzkzcxscqqzesfcvpsctmnvchgmv/Build/Intermediates.noindex/BeBetter.build/Debug-iphonesimulator/BeBetter-mobile.build/Script-61934B22C82A8F45E2E37C49.sh (in target 'BeBetter-mobile' from project 'BeBetter')
    cd /Users/asnagni/project/system/BeBetter/proj.ios_mac
    /bin/sh -c /Users/asnagni/Library/Developer/Xcode/DerivedData/BeBetter-fzkzcxscqqzesfcvpsctmnvchgmv/Build/Intermediates.noindex/BeBetter.build/Debug-iphonesimulator/BeBetter-mobile.build/Script-61934B22C82A8F45E2E37C49.sh

mkdir -p /Users/asnagni/Library/Developer/Xcode/DerivedData/BeBetter-fzkzcxscqqzesfcvpsctmnvchgmv/Build/Products/Debug-iphonesimulator/BeBetter-mobile.app/Frameworks
rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/asnagni/Library/Developer/Xcode/DerivedData/BeBetter-fzkzcxscqqzesfcvpsctmnvchgmv/Build/Products/Debug-iphonesimulator/Bolts/Bolts.framework" "/Users/asnagni/Library/Developer/Xcode/DerivedData/BeBetter-fzkzcxscqqzesfcvpsctmnvchgmv/Build/Products/Debug-iphonesimulator/BeBetter-mobile.app/Frameworks"
building file list ... done

sent 190 bytes  received 20 bytes  420.00 bytes/sec
total size is 148472  speedup is 707.01
/Users/asnagni/project/system/BeBetter/proj.ios_mac/Pods/Target Support Files/Pods-BeBetter-mobile/Pods-BeBetter-mobile-frameworks.sh: line 144: ARCHS[@]: unbound variable
Command PhaseScriptExecution failed with a nonzero exit code


Showing Recent Messages
mkdir -p /Users/asnagni/Library/Developer/Xcode/DerivedData/BeBetter-fzkzcxscqqzesfcvpsctmnvchgmv/Build/Products/Debug-iphonesimulator/BeBetter-mobile.app/Frameworks

rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/asnagni/Library/Developer/Xcode/DerivedData/BeBetter-fzkzcxscqqzesfcvpsctmnvchgmv/Build/Products/Debug-iphonesimulator/Bolts/Bolts.framework" "/Users/asnagni/Library/Developer/Xcode/DerivedData/BeBetter-fzkzcxscqqzesfcvpsctmnvchgmv/Build/Products/Debug-iphonesimulator/BeBetter-mobile.app/Frameworks"

building file list ... done



sent 190 bytes  received 20 bytes  420.00 bytes/sec

total size is 148472  speedup is 707.01

/Users/asnagni/project/system/BeBetter/proj.ios_mac/Pods/Target Support Files/Pods-BeBetter-mobile/Pods-BeBetter-mobile-frameworks.sh: line 144: ARCHS[@]: unbound variable

Command PhaseScriptExecution failed with a nonzero exit code

**Comment by infosteo** [comment]
> Hi I infosteo. Did you have any chance with this issue.
> 
> Hi saghul, would you have any idea on how to solve this.

See my post in #8015: solved both problems.

_This worked for me:
. I downgraded cocoa pods from 1.10.0 to 1.9.3
. Executed pod install in iOS folder
. Opened project workspace in Xcode
. Compiled app
. Granted execution to run-packager-helper.command in Mac system preferences_

**Comment by saghul** [comment]
The cocoapods project may need the same flags.

**Comment by asnagni** [comment]
Ok I will try to use the cocoa pods and let you know what I get. It may easier.

**Comment by asnagni** [comment]
Hi guys,
   I tried everything that you guys suggested but unfortunately it is not working for me 😔. When I was on Xcode 11 and using Jitsi iOS SDK version 2.9.3 everything was working fine with no problem.

   When I migrated to Xcode 12.1.  I was no longer able to build and run the App.

So that said, are you guys sure that you are using Xcode 12.1 ?

Thank you,
Stay safe.

**Comment by asnagni** [comment]
Hi guys,
  I was able to fix the issue. The two frameworks were  set to "**Do not Embed**" in the "**Framework, Libraries, and Embedded Content**" section. I should set to "**Embed & Sign**".

By Setting the option to "Embed & Sign" my problem was fixed.

For anyone that may have this issue, you also need to make sure that the "Always Embed Swift Standard Libraries" option is set to "**Yes**" for your Project and your target.


Thank you very much,
Stay safe

**Comment by kanelloc** [comment]
> The two frameworks

Can you give a little help? Where did you find the section with the two frameworks to set them to "**Do not Embed**"?

**Comment by asnagni** [comment]
Hi Bob,
	Sure please see attachment. Look at the WebRTC option. I hope that helps.:

**Comment by aub-pankaj** [comment]
Hi Guys,

I am still facing the same issue and when I create a build using this framework in Xcode 11.6.
can anyone share a working solution?

Thank and Regards

**Comment by asnagni** [comment]
Hi,
	Where are you blocked exactly? 

Thank you,
Stay safe.

**Comment by aub-pankaj** [comment]
I have built a framework using the react native code but when I integrate that framework in my native ios code and run the project in the simulator I am getting below error.

/Users/pankaj/Pankaj_Data/iOS/remotepcmeeting/RemotePCMeeting.xcodeproj Building for iOS Simulator, but the linked and embedded framework 'JitsiMeet.framework' was built for iOS.

I tried to implement the above solution but still facing the same issue

**Comment by asnagni** [comment]
Hi,
	There is no need for you to rebuild it. You just need to download the latest version and follow the steps that I pointed out. I’m repeating them here again to make it easier:

	1) Download the latest framework version
	2) Add the framework into your project
	3) Make sure that for the JitsiMeet.Framework you select the option: Embed & Sign (please see screenshot)
 
![PastedGraphic-1](https://user-images.githubusercontent.com/37470668/104201595-eccfc900-53f7-11eb-9a86-db4856a662f7.png)

	4) Make sure that for the WebRtc.Framework you select the option: Embed & Sign (please see screenshot)
![PastedGraphic-2](https://user-images.githubusercontent.com/37470668/104201641-f6593100-53f7-11eb-85ea-5d765d79dec6.png)


	5) In the Build and Settings screen, make sure to define the valid architectures (VALID_ARCHS). Please see screeanshot: 
![PastedGraphic-3](https://user-images.githubusercontent.com/37470668/104201654-fb1de500-53f7-11eb-976e-a6d7d4a8edbc.png)



I hope that helps,
Thank you,
Stay safe.

**Comment by asnagni** [comment]
Hi,
	Please see my answer on the close issues. I added some screen shot to help you.

Thank you,
Stay safe.

**Comment by techychen** [comment]
Adding `VALID_ARCHS` to User defined settings helped me working. Thanks @asnagni
