### ISSUE TITLE
iOS endpointTextMessageReceived and chatMessaageReceived delegate not working

### ISSUE THREAD

**Issue by eemi2010** [jitsi/jitsi-meet#8979]
### Description:

endpointTextMessageReceived and chatMessaageReceived delegate methods are not working

### Steps to reproduce:

1.  Extends and Implement JitsiMeetViewDelegate
2.  set JitsiMeetView delegate to self.
3.  send text message from another client in the room. Sent from a JS client with room.sendTextMessage()

### Expected behavior:

iOS delegate method should trigger

### Actual behavior:
Delegate methods are not getting called

### Server information:

- Jitsi Meet version: Latest version
- Operating System: Ubuntu Linux

### Client information:

- Operating System: iOS
- iOS SDK 3.3.0

**Comment by saghul** [comment]
Have you tested SDK 3.3.0?

**Comment by saghul** [comment]
Ack.

**Comment by saghul** [comment]
@tmoldovan8x8 PTAL.

**Comment by eemi2010** [comment]
Hello folks,
Sorry to bother you. Is this. confirmed bug or are we just doing something wring. 
chatMessageReceived  on Android seems to work just fine.

**Comment by tmoldovan8x8** [comment]
Hi @eemi2010 in the delegate method for chatMessage there is indeed a typo and I fixed it. In what concerns the endpointTextMessage, those are working fine, but it should be send with the apiClient on the web https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe, i.e. api.executeCommand('sendEndpointTextMessage', 'receiverId', 'some text message').

**Comment by eemi2010** [comment]
Hello @tmoldovan8x8. Thx for fixing the typo :) . endpointTextMessageReceived and chatMessaageReceived are not working when the message is sent using the meet-jitsi-lib API (https://github.com/jitsi/lib-jitsi-meet). Both are correctly working on Android using meet-jitsi-lib . Is iOS restricted to the iFrame API only ?

**Comment by tmoldovan8x8** [comment]
I think there might be a confusion here and our naming might not be the most inspiring one :). So, there are two ways for 2 participants to exchange messages, endpointTextMessage and chatMessage. Both of them use different variations of the methods on JitsiConference object. The chat message will also be displayed in the chat window, both on mobile and web. When you call sendTextMessage(text) on the conference, you actually want to send a chat message, so on Android you got the CHAT_MESSAGE_RECEIVED as you should, on iOS, due to the typo you don't. On iOS, until we release this fix, you will only see it in the chat window.  EndpointTextMessage is working fine both on Android, iOS and web, but this is to be sent either through the externalApi, as shown above, or with the sendEnpointMessage method on the conference, conference.sendEndpointMessage(to, {
                name: ENDPOINT_TEXT_MESSAGE_NAME,
                text: message
            });

Hopes this makes sense.

**Comment by eemi2010** [comment]
Makes  sense now. Indeed EndpointTextMessage is working. I was using the API wrongly. Looking forward for the next release with the ChatMessage fix. Thanks a lot for your time and explanation.

**Comment by eemi2010** [comment]
Hey there.

The release not of  3.4.0 on ios says the the typo (chatMessaageReceived)has been fixed in JitsiMeetViewDelegate(https://github.com/jitsi/jitsi-meet-release-notes/blob/master/CHANGELOG-MOBILE-SDKS.md). But I still see it on sdk 3.4.1. M I doing sometihng wrong ? 
Cheets

**Comment by eemi2010** [comment]
Sorry. I had a corrupted pod installation. Please ignore the previous comment.
